# Generated by Django 5.1.2 on 2026-01-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'autores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'carreras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('codigo_cota', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('id_carrera', models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.carreras')),
            ],
            options={
                'db_table': 'documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadosEjemplar',
            fields=[
                ('id_estado_ejemplar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estados_ejemplar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prestamos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('pasillo', models.CharField(blank=True, max_length=50, null=True)),
                ('estante', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_completa', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'ubicaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentoAcademico',
            fields=[
                ('id_documento', models.OneToOneField(db_column='id_documento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.documentos')),
                ('tutor_academico', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'documento_academico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InformePasantiaDetalle',
            fields=[
                ('id_documento', models.OneToOneField(db_column='id_documento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.documentos')),
                ('autor_academico', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'informe_pasantia_detalle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibroDetalle',
            fields=[
                ('id_documento', models.OneToOneField(db_column='id_documento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.documentos')),
                ('area_de_conocimiento', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'libro_detalle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentoAutores',
            fields=[
                ('id_documento_autor', models.AutoField(primary_key=True, serialize=False)),
                ('id_autor', models.ForeignKey(db_column='id_autor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.autores')),
                ('id_documento', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.DO_NOTHING, to='core.documentos')),
            ],
            options={
                'db_table': 'documento_autores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ejemplares',
            fields=[
                ('id_ejemplar', models.AutoField(primary_key=True, serialize=False)),
                ('tomo', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_fisica', models.IntegerField()),
                ('codigo_cota', models.CharField(blank=True, max_length=50, null=True)),
                ('id_documento', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.DO_NOTHING, to='core.documentos')),
                ('id_estado_ejemplar', models.ForeignKey(db_column='id_estado_ejemplar', on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadosejemplar')),
                ('id_ubicacion', models.ForeignKey(blank=True, db_column='id_ubicacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ubicaciones')),
            ],
            options={
                'db_table': 'ejemplares',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id_detalle_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('id_ejemplar', models.ForeignKey(db_column='id_ejemplar', on_delete=django.db.models.deletion.DO_NOTHING, to='core.ejemplares')),
                ('id_prestamo', models.ForeignKey(db_column='id_prestamo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.prestamos')),
            ],
            options={
                'db_table': 'detalle_prestamo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='documentos',
            name='id_tipo_documento',
            field=models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipodocumento'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='core.roles')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='prestamos',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios'),
        ),
    ]
